AdaBoostClassifier:
  functions:
    model_create:
      algorithm: SAMME.R
      learning_rate: 1.0
      n_estimators: 50
  model:
    model_class: sklearn.ensemble.AdaBoostClassifier
    model_type: classification
