BaggingClassifier:
  functions:
    model_create:
      bootstrap: true
      bootstrap_features: false
      max_features: 1.0
      max_samples: 1.0
      n_estimators: 10
      n_jobs: -1
      oob_score: false
      verbose: 0
      warm_start: false
  model:
    model_class: sklearn.ensemble.BaggingClassifier
    model_type: classification
