BayesianRidge:
  functions:
    model_create:
      alpha_1: 1.0e-06
      alpha_2: 1.0e-06
      compute_score: false
      copy_X: true
      fit_intercept: true
      lambda_1: 1.0e-06
      lambda_2: 1.0e-06
      n_iter: 300
      normalize: true
      tol: 0.001
      verbose: false
  model:
    model_class: sklearn.linear_model.BayesianRidge
    model_type: regression
