DecisionTreeRegressor:
  functions:
    model_create:
      criterion: mse
      min_impurity_decrease: 0.0
      min_samples_leaf: 1
      min_samples_split: 2
      min_weight_fraction_leaf: 0.0
      presort: false
      splitter: best
  model:
    model_class: sklearn.tree.DecisionTreeRegressor
    model_type: regression
