functions:
  model_create:
    copy_X: true
    cv: warn
    eps: 0.001
    fit_intercept: true
    l1_ratio: 0.5
    max_iter: 1000
    n_alphas: 100
    normalize: true
    positive: false
    precompute: auto
    selection: cyclic
    tol: 0.0001
    verbose: 0
model:
  model_class: sklearn.linear_model.OrthogonalMatchingPursuit
  model_type: regression
