ExtraTreesClassifier:
  functions:
    model_create:
      bootstrap: false
      criterion: gini
      max_features: auto
      min_impurity_decrease: 0.0
      min_samples_leaf: 1
      min_samples_split: 2
      min_weight_fraction_leaf: 0.0
      n_estimators: 100
      n_jobs: -1
      oob_score: false
      verbose: 0
      warm_start: false
  hyper_parameter_optimization:
    enable: true
    algorithm: tpe
    max_evals: 100
    show_progressbar: true
    space:
      model_create:
        criterion:
          - choice
          - ['gini', 'entropy']
        max_depth:
          - uniformint
          - 2
          - 30
        max_features:
          - uniform
          - 0.3
          - 1.0
        min_samples_split:
          - uniformint
          - 2
          - 20
        min_samples_leaf:
          - uniformint
          - 1
          - 100
        n_estimators:
          - uniformint
          - 2
          - 1000
  model:
    model_class: sklearn.ensemble.ExtraTreesClassifier
    model_type: classification
