MultinomialNB:
  # Requires all inputs to be non-negative: Disabled
  # You can enable this if your data fits the requirements
  enable: false
  functions:
    model_create:
      alpha: 1.0
      fit_prior: true
  model:
    model_class: sklearn.naive_bayes.MultinomialNB
    model_type: classification
