NuSVR:
  functions:
    model_create:
      C: 1.0
      cache_size: 200
      coef0: 0.0
      degree: 3
      gamma: scale
      kernel: rbf
      max_iter: -1
      nu: 0.5
      shrinking: true
      tol: 0.001
      verbose: false
  model:
    model_class: sklearn.svm.NuSVR
    model_type: regression
