NuSVC:
  # Requires tunning of 'nu' parameters, otherwise throws an error.
  # Disabled by default.
  enable: false
  functions:
    model_create:
      cache_size: 200
      coef0: 0.0
      decision_function_shape: ovr
      degree: 3
      gamma: scale
      kernel: rbf
      max_iter: -1
      nu: 0.5
      probability: false
      shrinking: true
      tol: 0.001
      verbose: false
  model:
    model_class: sklearn.svm.NuSVC
    model_type: classification
