PassiveAggressiveClassifier:
  functions:
    model_create:
      C: 1.0
      average: false
      early_stopping: false
      fit_intercept: true
      loss: hinge
      max_iter: 1000
      n_iter_no_change: 5
      shuffle: true
      tol: 0.001
      validation_fraction: 0.1
      verbose: 0
      warm_start: false
  model:
    model_class: sklearn.linear_model.PassiveAggressiveClassifier
    model_type: classification
