Perceptron:
  functions:
    model_create:
      alpha: 0.0001
      early_stopping: false
      eta0: 1.0
      fit_intercept: true
      max_iter: 1000
      n_iter_no_change: 5
      random_state: 0
      shuffle: true
      tol: 0.001
      validation_fraction: 0.1
      verbose: 0
      warm_start: false
  model:
    model_class: sklearn.linear_model.Perceptron
    model_type: classification
