functions:
  model_create:
    C: 1.0
    cache_size: 200
    coef0: 0.0
    degree: 3
    epsilon: 0.1
    gamma: auto_deprecated
    kernel: rbf
    max_iter: -1
    shrinking: true
    tol: 0.001
    verbose: false
model:
  model_class: sklearn.svm.SVR
  model_type: regression
