dataset:
  dataset_name: 'example_01'
  dataset_path: 'data/example_01'

model:
  model_name: 'example_01'
  model_path: 'data/example_01/model'

functions:
    dataset_create:
      num_samples: 1000
    dataset_split:
      split_validate: 0.2
      split_test: 0.0
    model_create:
        num_neurons: 3
    model_train:
      epochs: 20
      learning_rate: 0.3
