
logger:

dataset:
  dataset_type: 'df'
  dataset_name: 'linear3c'
  dataset_path: 'data/linear3c'
  outputs: ['y']

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: false

dataset_preprocess:
  enable: true
  normalize:
    standard: true
    skip: ['y']

dataset_transform:
  enable: true
  remove_missing_outputs: true

model:
  enable: false
  model_type: regression
  model_name: 'linear3c'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/linear3c/model'
  is_save_model_pickle: True
  is_save_model_method: True
  is_save_model_method_ext: 'model'
  is_save_params: True
  is_save_test_pickle: True
  is_save_train_pickle: false
  is_save_validate_pickle: false

hyper_parameter_optimization:
    enable: false
    show_progressbar: True
    algorithm: 'tpe'
    max_evals: 5
    space:
        model_create:
            n_estimators: ['randint', 1000]
            min_samples_leaf: ['randint', 100]
            max_features: ['uniform', 0.0, 1.0]

functions:
    dataset_augment:
    dataset_create:
    dataset_load:
    dataset_save:
    dataset_split:
      n: 1000
    dataset_preprocess:
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7
    model_evaluate:
    model_save:
    model_train:

model_search:
  enable: False
  models: !include models_search/*.yaml
