logger:
  plots_path: 'logml_plots/linear100c' # Path where plots are saved

dataset:
  dataset_type: 'df'
  dataset_name: 'linear100c'
  dataset_path: 'data/linear100c'
  outputs: ['y']

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: true
  is_permutataion_extra_trees: false
  is_permutataion_gradient_boosting: false
  is_permutataion_random_forest: false
  is_rfe_model: false

dataset_preprocess:
  enable: true
  normalize:
    standard: true
    skip: ['y']

dataset_transform:
  enable: true

model:
  enable: false
  model_type: regression
  model_name: 'linear100c'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/linear100c/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: false
  models: !include models_search/*.yaml
