logger:
  plots_path: 'logml_plots/linear3'

dataset:
  dataset_type: 'df'
  dataset_name: 'linear3'
  dataset_path: 'data/linear3'
  outputs: ['y']

dataset_preprocess:
  enable: true
  impute:
    median: true
  normalize:
    standard: true
    skip: ['y']

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: true
  enable_na: false

  is_model_dropcol: false
  is_model_permutation: true
  is_model_skmodel: false

  is_permutation_extra_trees: false
  is_permutation_gradient_boosting: false
  is_permutation_random_forest: true

  permutation_iterations_random_forest: 2

cross_validation:
    # Set to 'false' to disable cross validation
    enable: true
    KFold:
        n_splits: 3

model:
  enable: false
  model_type: regression
  model_name: 'linear3'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/linear3/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: false
  models: !include models_search/*.yaml
