logger:
  disable_plots: true
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_preprocess:
  enable: true
  categories:
    c1: ['low', 'mid', 'high']
  one_hot: []
  one_hot_max_cardinality: 7
  impute:
    median: true
  normalize:
    enable: false
    standard: true

dataset_augment:
  enable: false

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: true
  enable_na: true

  permutation_iterations_gradient_boosting: 3
  permutation_iterations_extra_trees: 3
  permutation_iterations_random_forest: 3

  wilks_null_model_variables: ['x4', 'x5']

analysis:
  enable: false
  gene_set_enrichment:
      enable: true

cross_validation:
    enable: true
    KFold:
        n_splits: 100

model:
  enable: true
  model_type: regression
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.0
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

hyper_parameter_optimization:
  enable: true
  algorithm: tpe
  max_evals: 3
  show_progressbar: true
  space:
    model_create:
      n_estimators:
        - uniformint
        - 2
        - 1000

model_search:
  enable: true
  models: !include models_search/*.yaml
