logger:
  disable_plots: false
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_preprocess:
  enable: true
  categories:
    c1: ['low', 'mid', 'high']
  one_hot: []
  one_hot_max_cardinality: 7
  impute:
    median: true
  normalize:
    enable: false
    standard: true

dataset_augment:
  enable: false

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: false
  enable_na: false
  is_dropcol_extra_trees: true
  is_dropcol_gradient_boosting: true
  is_dropcol_random_forest: true
  is_fip_random_forest: true
  is_fip_extra_trees: true
  is_fip_gradient_boosting: true
  is_permutation_extra_trees: true
  is_permutation_gradient_boosting: true
  is_permutation_random_forest: true
  is_regularization_lasso: true
  is_regularization_ridge: true
  is_regularization_lars: true
  is_rfe_model: true
  is_rfe_model_lasso: true
  is_rfe_model_ridge: true
  is_rfe_model_lars_aic: true
  is_rfe_model_lars_bic: true
  is_rfe_model_random_forest: true
  is_rfe_model_extra_trees: true
  is_rfe_model_gradient_boosting: true
  is_skmodel_extra_trees: true
  is_skmodel_gradient_boosting: true
  is_skmodel_random_forest: true
  is_select: true
  is_linear_pvalue: true
  is_tree_graph: true
  is_wilks: true

  permutation_iterations_gradient_boosting: 3
  permutation_iterations_extra_trees: 3
  permutation_iterations_random_forest: 3

  wilks_null_model_variables: ['x4', 'x5']


cross_validation:
    # Set to 'false' to disable cross validation
    enable: true
    KFold:
        n_splits: 3

analysis:
  enable: false
  gene_set_enrichment:
      enable: true

model:
  enable: true
  model_type: regression
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.0
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: true
  models: !include models_search/*.yaml
