logger:
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: true

  # Enable "Feature Importance using Permutations" (for different models)
  is_fip_random_forest: true
  is_fip_extra_trees: false
  is_fip_gradient_boosting: false

  # Regularization methods
  # Enable regularization methods (for different models)
  is_regularization_lasso: false
  is_regularization_ridge: false
  is_regularization_lars: false
  # Number of Cross-validation in regularization methods
  regularization_model_cv: 10

  # Enable Recursive Feature Elimination (for different models)
  is_rfe_model: false
  is_rfe_model_lasso: false
  is_rfe_model_ridge: false
  is_rfe_model_lars_aic: false
  is_rfe_model_lars_bic: false
  is_rfe_model_random_forest: false
  is_rfe_model_extra_trees: false
  is_rfe_model_gradient_boosting: false
  rfe_model_cv: 0  # Number of Corss-validations in Recursive Feature Elimination methods

  # Enable model selection methods (SelectFdr / SelectKBest)
  is_select: false

  # Tree graph
  is_tree_graph: false
  tree_graph_max_depth: 4  # Number of layers to show in graph

  is_wilks: true
  wilks_null_model_variables: ['x3']

dataset_preprocess:
  enable: false

dataset_transform:
  enable: false

model:
  enable: true
  model_type: regression
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.1
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

cross_validation:
    enable: false
    KFold:
        n_splits: 5

model_search:
  enable: false
  models: !include models_search/*.yaml
