logger:
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_explore:
  enable: false

dataset_preprocess:
  enable: false

dataset_transform:
  enable: false

dataset_augment:
  enable: true
  pca:
    pca_1:
      num: 2
      fields: ['x.*']
  nmf:
    nmf_1:
      num: 3
      fields: ['z.*', 'y.*']

dataset_feature_importance:
  enable: false

model:
  enable: false
  model_type: regression
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: false
  models: !include models_search/*.yaml
