logger:
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_preprocess:
  enable: false

dataset_explore:
  enable: false

dataset_augment:
  enable: false

dataset_feature_importance:
  enable: true
  enable_na: false
  is_fip_random_forest: false
  is_fip_extra_trees: false
  is_fip_gradient_boosting: false
  is_regularization_lasso: false
  is_regularization_ridge: false
  is_regularization_lars: false
  is_rfe_model: false
  is_rfe_model_lasso: false
  is_rfe_model_ridge: false
  is_rfe_model_lars_aic: false
  is_rfe_model_lars_bic: false
  is_rfe_model_random_forest: false
  is_rfe_model_extra_trees: false
  is_rfe_model_gradient_boosting: false
  is_select: false
  is_linear_pvalue: false
  is_tree_graph: false
  #
  is_wilks: true
  wilks_null_model_variables: ['x4', 'x5']


model:
  enable: false
  model_type: classification
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: false
  models: !include models_search/*.yaml
