logger:
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_preprocess:
  enable: true
  impute:
    median: true
  normalize:
    standard: true

dataset_augment:
  # Set to 'false' to disable this step
  enable: true
  # TODO: add_interactions: ['*', '-', '+', '/']

  # Add principal componenets
  # After the 'pca', you can add several "sub-sections":
  #   name:                 # Unique name, used to add PCA fields on each sample (name_1, name_2, ... name_num)
  #     num: 2              # Number of PCA componenets to add
  #     fields: ['x.*']     # List of regular expression to match field names (only fields matching this list will be used)
  pca:
    pca_a:
      num: 2
      fields: ['x0', 'x1', 'x2']
    pca_b:
      num: 3
      fields: ['x3', 'x4', 'x5']
    pca_c:
      num: 3
      fields: ['x0', 'x3', 'x5']

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: false
  enable_na: true
  is_fip_random_forest: true
  is_fip_extra_trees: true
  is_fip_gradient_boosting: true
  is_regularization_lasso: true
  is_regularization_ridge: true
  is_regularization_lars: true
  is_rfe_model: true
  is_rfe_model_lasso: true
  is_rfe_model_ridge: true
  is_rfe_model_lars_aic: true
  is_rfe_model_lars_bic: true
  is_rfe_model_random_forest: true
  is_rfe_model_extra_trees: true
  is_rfe_model_gradient_boosting: true
  is_select: true
  is_linear_pvalue: true
  is_tree_graph: true
  #
  is_wilks: true
  wilks_null_model_variables: ['x4', 'x5']


model:
  enable: false
  model_type: classification
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: false
  models: !include models_search/*.yaml
