logger:
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_preprocess:
  enable: true
  impute:
    median: true
  normalize:
    standard: true

dataset_augment:
  # Set to 'false' to disable this step
  enable: true
  and:
    and_3:
      order: 4             # Number of fields combined in this operationb (can be two or more)
      min_non_zero: 50       # Min number of non-zero fields when adding this new column, If more than 1.0, then count_non_zero >= min_non_zero. If < 1.0 then it's a percentage, i.e (count_non_zero/total) >= min_non_zero
      fields: ['x.*']

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: true
  enable_na: false
  is_dropcol_extra_trees: false
  is_dropcol_gradient_boosting: false
  is_dropcol_random_forest: false
  is_fip_random_forest: false
  is_fip_extra_trees: false
  is_fip_gradient_boosting: false
  is_permutation_extra_trees: false
  is_permutation_gradient_boosting: false
  is_permutation_random_forest: false
  is_regularization_lasso: false
  is_regularization_ridge: false
  is_regularization_lars: false
  is_rfe_model: false
  is_rfe_model_lasso: false
  is_rfe_model_ridge: false
  is_rfe_model_lars_aic: false
  is_rfe_model_lars_bic: false
  is_rfe_model_random_forest: false
  is_rfe_model_extra_trees: false
  is_rfe_model_gradient_boosting: false
  is_skmodel_extra_trees: false
  is_skmodel_gradient_boosting: false
  is_skmodel_random_forest: false
  is_select: false
  is_linear_pvalue: false
  is_tree_graph: false
  #
  is_wilks: false
  wilks_null_model_variables: ['x4', 'x5']

cross_validation:
    # Set to 'false' to disable cross validation
    enable: false
    KFold:
        n_splits: 5

model:
  enable: false
  model_type: regression
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: false
  models: !include models_search/*.yaml
