logger:
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_preprocess:
  enable: true
  impute:
    median: true
  normalize:
    standard: true

dataset_explore:
  enable: true

dataset_feature_importance:
  enable: true
  enable_na: true
  is_fip_random_forest: true
  is_fip_extra_trees: true
  is_fip_gradient_boosting: true
  is_regularization_lasso: true
  is_regularization_ridge: true
  is_regularization_lars: true
  is_rfe_model: true
  is_rfe_model_lasso: true
  is_rfe_model_ridge: true
  is_rfe_model_lars_aic: true
  is_rfe_model_lars_bic: true
  is_rfe_model_random_forest: true
  is_rfe_model_extra_trees: true
  is_rfe_model_gradient_boosting: true
  is_select: true
  is_linear_pvalue: true
  is_tree_graph: true
  #
  is_wilks: true
  wilks_null_model_variables: ['x4', 'x5']


model:
  enable: true
  model_type: classification
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

model_search:
  enable: true
  models: !include models_search/*.yaml
