logger:
  plots_path: 'logml_plots/zzz'

dataset:
  dataset_type: 'df'
  dataset_name: 'zzz'
  dataset_path: 'data/zzz'
  outputs: ['y']

dataset_explore:
  enable: false

dataset_feature_importance:
  enable: false

dataset_preprocess:
  enable: true
  impute:
    mean: true

dataset_transform:
  enable: true

model:
  enable: true
  model_type: regression
  model_name: 'zzz'
  model_class: sklearn.ensemble.RandomForestRegressor
  model_path: 'data/zzz/model'

functions:
    dataset_split:
        split_validate: 0.2
        split_test: 0.0
    model_create:
      n_estimators: 30
      min_samples_leaf: 3
      max_features: 0.7

cross_validation:
    enable: true
    KFold:
        n_splits: 3

model_search:
  enable: true
  models: !include models_search/*.yaml
