ExtraTreesRegressor:
  functions:
    model_create:
      bootstrap: false
      criterion: mse
      max_features: auto
      min_impurity_decrease: 0.0
      min_samples_leaf: 1
      min_samples_split: 2
      min_weight_fraction_leaf: 0.0
      n_estimators: warn
      n_jobs: -1
      oob_score: false
      verbose: 0
      warm_start: false
  hyper_parameter_optimization:
    enable: true
    algorithm: tpe
    max_evals: 100
    show_progressbar: true
    space:
      model_create:
        # criterion: [choice, ['mse', 'mae']]
        # max_depth: ['quniform', 2, 30]
        # max_features: ['uniform', 0.3, 1.0]
        # min_samples_split: ['quniform', 2 20]
        # min_samples_leaf: ['quniform', 1, 100]
        n_estimators: ['quniform', 2, 10000]
  model:
    model_class: sklearn.ensemble.ExtraTreesRegressor
    model_type: regression
