RandomForestRegressor:
  functions:
    model_create:
      bootstrap: true
      criterion: mse
      max_features: auto
      min_impurity_decrease: 0.0
      min_samples_leaf: 1
      min_samples_split: 2
      min_weight_fraction_leaf: 0.0
      n_jobs: -1
      n_estimators: 100
      oob_score: false
      verbose: 0
      warm_start: false
  hyper_parameter_optimization:
    enable: true
    algorithm: tpe
    max_evals: 5
    show_progressbar: true
    space:
      model_create:
        max_features:
        - uniform
        - 0.3
        - 1.0
        min_samples_leaf:
        - randint
        - 100
        n_estimators:
        - randint
        - 1000
  model:
    model_class: sklearn.ensemble.RandomForestRegressor
    model_type: regression
