site_name: LogMl - AI/ML automation framwork
nav:
  - Home: index.md
  - About: about.md
  - Manual:
    - 'Overview': zzz.md
    - 'Custom Functions': custom_functions.md
    - 'Examples': examples_custom_fucntions.md
theme: readthedocs
