site_name: LogMl
nav:
  - Home: index.md
  - About: about.md
  - Manual:
    - 'Overview': overview.md
    - 'Install': install.md
    - 'Introduction': introduction.md
    - 'Introduction command line': introduction_cmd.md
    - 'Introduction Jupyter Notebooks': introduction_juppyter.md
    - 'Logging': logging.md
    - 'Workflow': workflow.md
    - 'Workflow: Datasets': datasets.md
    - 'Workflow: Explore': explore.md
    - 'Workflow: Feature importance': feature_importance.md
    - 'Workflow: Model': model.md
    - 'Workflow: Hyper-parameter tunnig': model_hyperopt.md
    - 'Workflow: Model Search': model_search.md
    - 'Cross validation': cross_validation.md
    - 'Examples: Custom functions': examples_custom_fucntions.md
# theme: readthedocs
